/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package options;

/**
 *
 * @author Santiago
 */
public class Options extends javax.swing.JFrame {

    /**
     * Creates new form OPtions
     */
    public Options() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gender = new javax.swing.ButtonGroup();
        Color = new javax.swing.ButtonGroup();
        Man = new javax.swing.JRadioButton();
        Woman = new javax.swing.JRadioButton();
        Other = new javax.swing.JRadioButton();
        Red = new javax.swing.JRadioButton();
        Blue = new javax.swing.JRadioButton();
        Green = new javax.swing.JRadioButton();
        Send = new javax.swing.JButton();
        Result = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Gender.add(Man);
        Man.setText("Hombre");
        Man.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManActionPerformed(evt);
            }
        });

        Gender.add(Woman);
        Woman.setText("Mujer");

        Gender.add(Other);
        Other.setText("Otro");

        Color.add(Red);
        Red.setText("Rojo");

        Color.add(Blue);
        Blue.setText("Azul");

        Color.add(Green);
        Green.setText("Verde");

        Send.setText("Enviar");
        Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendActionPerformed(evt);
            }
        });

        Result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Other)
                            .addComponent(Woman))
                        .addGap(138, 157, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Blue)
                            .addComponent(Green))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Man)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Red)
                        .addGap(30, 30, 30))))
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(Send)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Man)
                    .addComponent(Red))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Woman)
                    .addComponent(Blue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Other)
                    .addComponent(Green))
                .addGap(18, 18, 18)
                .addComponent(Send, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(Result)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManActionPerformed
     
    }//GEN-LAST:event_ManActionPerformed

    private void SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendActionPerformed
        if(this.Man.isSelected() && this.Red.isSelected()){
            Result.setText("Hombre del maravilloso Santa Fe");
	}else if(this.Man.isSelected() && this.Blue.isSelected()){
            Result.setText("Hombre de la gallina");
        }else if(this.Man.isSelected() && this.Green.isSelected()){
            Result.setText("Hombre paisa :/");
        }else if(this.Woman.isSelected() && this.Red.isSelected()){
            Result.setText("Dama del maravilloso Santa Fe");
        }else if(this.Woman.isSelected() && this.Blue.isSelected()){
            Result.setText("Mujer lastimosamente de millnarios");
        }else if(this.Woman.isSelected() && this.Green.isSelected()){
            Result.setText("Mujer paisa :/");
        }else if(this.Other.isSelected() && this.Red.isSelected()){
            Result.setText("Quien sabe que sera pero es de Santa fe :D");
        }else if(this.Other.isSelected() && this.Blue.isSelected()){
            Result.setText("Ni sabe que es y escogio a la gallina");
        }else if(this.Other.isSelected() && this.Green.isSelected()){
            Result.setText("No sabe que es pero nacio en Medellin :/");
        }
    }//GEN-LAST:event_SendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Options().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Blue;
    private javax.swing.ButtonGroup Color;
    private javax.swing.ButtonGroup Gender;
    private javax.swing.JRadioButton Green;
    private javax.swing.JRadioButton Man;
    private javax.swing.JRadioButton Other;
    private javax.swing.JRadioButton Red;
    private javax.swing.JLabel Result;
    private javax.swing.JButton Send;
    private javax.swing.JRadioButton Woman;
    // End of variables declaration//GEN-END:variables
}
